var helpers = require("../util/helpers")

module.exports = function(req, next){
  if (req.argv.help || req.argv.h) {
    helpers
      //.log()
      //.log("  " + req.config.name.bold, "– single command web publishing.".grey, ("(v" + req.pkg.version + ")"). grey)
      .log()
      .log("  Main Usage:".grey)
      .log("    "+ req.config.name +" <project-path> <domain>       publish project to domain")
      .log()
      .log("  Project Commands:".grey)
      .log("    "+ req.config.name +" cutover <preview>             change to latest revision")
      .log("    "+ req.config.name +" discard <preview>             remove revision from system")
      .log("    "+ req.config.name +" rollfore <domain>             change to next revision")
      .log("    "+ req.config.name +" rollback <domain>             change to previous revision")
      .log("    "+ req.config.name +" teardown <domain>             tear down a published project")
      .log("    "+ req.config.name +" invite <domain> <emails>      invites user to be a contributor")
      .log("    "+ req.config.name +" revoke <domain> <emails>      revokes contributor rights")
      .log("    "+ req.config.name +" list <domain>                 list all revisions")
      .log("    "+ req.config.name +" ssl <domain> <pempath>        publish .pem file for SSL support")
      .log()
      .log("  Account Commands:".grey)
      .log("    "+ req.config.name +" whoami                        show who you are logged in as")
      .log("    "+ req.config.name +" login                         only performs authentication step")
      .log("    "+ req.config.name +" logout                        expire local token")
      .log("    "+ req.config.name +" token                         create token for automation purposes")
      .log("    "+ req.config.name +" plan                          upgrade or downgrade account plan")
      .log("    "+ req.config.name +" list                          list all projects")
      .log()
      .log("  Options:".grey)
      .log("    -s, --preview                       (when publishing) publishes preview")
      .log("    -t, --token                         pass in token to use for call")
      .log("    -V, --version                       show the version number")
      .log("    -h, --help                          show this help message")
      .log()
      .log("  Examples:".grey)
      .log("    "+ req.config.name +" www example.com               publishes www directory to example.com")
      .log("    "+ req.config.name +" . example.com --preview       publishes current directory for preview")
      .log("    "+ req.config.name +" cutover example.com           switches latest preview to production")
      .log("    "+ req.config.name +" . _                           publish current dir to random subdomain")
      // .log()
      // .log("  Guides:".grey)
      // .log("    Getting started     " + "surge.sh/help/getting-started-with-surge".underline.grey)
      // .log("    Custom domains      " + "surge.sh/help/adding-a-custom-domain".underline.grey)
      // .log("    Additional help     " + "surge.sh/help".underline.grey)
      .log()
      .log("  When in doubt, run ".grey + req.config.name.green.underline + " from within your project directory.".grey)
      .log()

  } else {
    next()
  }
}
