module.exports = [
  require("./whitelist"),
  require("./endpoint"),
  require("./pkg"),
  require("./version"),
  require("./help"),
  require("./creds"),
  require("./whoami"),
  require("./logout"),
  require("./tokencheck"),
  require("./email"),
  require("./auth"),
  require("./login"),
  // require("./teardown"),
  // require("./list"),
  // require("./shorthand"),
  // require("./project"),
  // require("./size"),
  // require("./domain"),
  // // require("./deploy"),
  // // require("./ipaddress"),
  require("./log")
]
