module.exports = [
  //require("./log"),
  require("./endpoint"),
  require("./pkg"),
  require("./version"),
  require("./help"),
  require("./whoami"),
  require("./logout"),
  require("./shorthand"),
  require("./creds"),
  require("./auth"),
  require("./project"),
  require("./size"),
  //require("./prep"),
  require("./domain"),
  //require("./confirm"),
  require("./deploy"),
  require("./ipaddress")
]
